### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by adispi** [ik5/display-quotes#1]
Hint: Start of reading config file /etc/fpc.cfg
Hint: End of reading config file /etc/fpc.cfg
Free Pascal Compiler version 2.4.4-2ubuntu1 [2011/09/27] for i386
Copyright (c) 1993-2010 by Florian Klaempfl
Target OS: Linux for i386
Compiling quotes.lpr
Compiling /home/ik/display-quotes/src/forms/untdisplayquotes.pas
Compiling /home/ik/display-quotes/src/forms/untsearchdialog.pas
Compiling /home/ik/display-quotes/src/units/untfindquote.pas
/home/ik/display-quotes/src/units/untfindquote.pas(51,13) Error: Exit with argument can't be used here
/home/ik/display-quotes/src/units/untfindquote.pas(117) Fatal: There were 1 errors compiling module, stopping

**Comment by adispi** [comment]
if i remove the nil from the exit() statement, i get this error:

/home/ik/display-quotes/src/units/untfindquote.pas(55,20) Hint: Parameter "sub" not used
/home/ik/display-quotes/src/units/untfindquote.pas(71,20) Hint: Parameter "s" not used
/home/ik/display-quotes/src/units/untsavesettings.pas(69,39) Hint: Unit "untDisplayQuotes" not used in untSaveSettings
../units/untgtknotify.pas(11,3) Fatal: Can't find unit libnotify used by untGTKNotify

**Comment by ik5** [comment]
The first problem was fixed.
The second part, require from you to import also the sub module of libnotify.
If you used Git, it should have provided it as well, but in the zip/tar files they do not exists.

**Comment by adispi** [comment]
i have found why libnotify does not clone.
cat .gitmodules 
[submodule "src/libnotify"]
        path = src/libnotify
        url = git@github.com:ik5/libnotify-fpc.git

this uses your private path and not the public path.
